anyhow = "1"
serde_json = "1"
>>>>>>> 7e2ea3a07bd5fec5efe78199e43a988ddc64bf65
[package]
name = "tonledb-wire-pg"
version = "0.1.0"
edition = "2021"

[dependencies]
tonledb-core = { path = "../tonledb-core" }
tonledb-sql = { path = "../tonledb-sql" }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
serde_json = "1.0"
=======
anyhow = "1"
serde_json = "1"
>>>>>>> 7e2ea3a07bd5fec5efe78199e43a988ddc64bf65
