[package]
name = "tonledb-core"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
parking_lot = "0.12"
bytes = "1"
anyhow = "1"
hex = "0.4"