apiVersion: v1
kind: Namespace
metadata: { name: tonledb, labels: { pod-security.kubernetes.io/enforce: restricted } }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: tonledb, namespace: tonledb }
spec:
  replicas: 1
  selector: { matchLabels: { app: tonledb } }
  template:
    metadata: { labels: { app: tonledb } }
    spec:
      securityContext: { runAsNonRoot: true, seccompProfile: { type: RuntimeDefault } }
      containers:
      - name: tonledb
        image: tonledb:secure
        ports:
        - { containerPort: 8443, name: https }
        - { containerPort: 9464, name: metrics }
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: { drop: ["ALL"] }
          readOnlyRootFilesystem: true
        resources:
          requests: { cpu: "250m", memory: "256Mi" }
          limits:   { cpu: "1",    memory: "1Gi" }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: { name: allow-gateway-only, namespace: tonledb }
spec:
  podSelector: { matchLabels: { app: tonledb } }
  ingress:
  - from:
    - namespaceSelector: { matchLabels: { name: gateway } }
    ports:
    - { port: 8443, protocol: TCP }
