[package]
name = "tonledb-arrow"
version = "0.1.0"
edition = "2021"

[dependencies]
tonledb-core = { path = "../tonledb-core" }
arrow = "52.0"
parquet = "52.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"