[package]
name = "tonledb-nosql-doc"
version = "0.1.0"
edition = "2021"

[dependencies]
tonledb-core = { path = "../tonledb-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
nanoid = "0.4"
